### ISSUE TITLE
No template page or form builder.

### ISSUE THREAD

**Issue by TheMacU** [everpress-co/mailster-block-forms#1]
### Describe the bug

When I click add new in block forms no template chooser appears as shown in the guide. It's just a basic post editor. 

### Steps to Reproduce

Click on "Create New Form"
-No templates or form builder appears. 

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/84143362/187743731-00eaacda-5c1a-4013-b514-58a8f14888f2.mov

### Environment information

Safari 16.0. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by evrpress** [comment]
Hi there!

Thanks for the feedback! Do you use any plugin to disable to block editor like the [Classic Editor](https://wordpress.org/plugins/classic-editor/) plugin?

If so you have to disable it to use it.

**Comment by evrpress** [comment]
@TheMacU can you please check if 0.1.2 fixes this?

**Comment by ymarc77** [comment]
On my site similar problem was caused by plugin "Convert to Blocks" – https://pl.wordpress.org/plugins/convert-to-blocks/
