### ISSUE TITLE
Add button style on hover

### ISSUE THREAD

**Issue by codeby** [everpress-co/mailster-block-forms#12]
### Is your enhancement related to a problem? Please describe.

I suggest adding the ability to change the button style when hovering (color, button shadow, font color, border color).

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by evrpress** [comment]
We like to stick to native button options to not reinvent the wheel in case there are more options for buttons available. You can meanwhile use the Custom CSS panel to define custom rules.
