### ISSUE TITLE
Custom fields are not working with underline

### ISSUE THREAD

**Issue by LaurGhe** [everpress-co/mailster-block-forms#19]
### Describe the bug

As soon as the tag name contains an underscore the field no longer shows up as block in the block editor. Ticket 42056.

### Steps to Reproduce

1. Go to Newsletter > Settings > Subscribers
2. Add a custom field with an underline in the tag. For instance: test_field
3. Save
4. Open a block form and try to add the new added custom field.

### Screenshots, screen recording, code snippet

![Captură_ecran_022924_101457_PM](https://github.com/everpress-co/mailster-block-forms/assets/108144934/32945da6-6f9c-4a80-b674-4fb4a105eb8c)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by evrpress** [comment]
fixed in core
