### ISSUE TITLE
Form templates are not loaded if the form is saved

### ISSUE THREAD

**Issue by LaurGhe** [everpress-co/mailster-block-forms#20]
### Describe the bug

The Form templates are not loaded if the form is saved. If the form is not saved, all the templates are loaded correctly.

### Steps to Reproduce

1. Create a new block form and save it.
2. Close the page.
3. Open for edit the new created form and click on the "Select template" button. 

### Screenshots, screen recording, code snippet

https://f.evp.to/i/zY22Y4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by evrpress** [comment]
Fixed in 4.1.5
