### ISSUE TITLE
Not all blocks are available

### ISSUE THREAD

**Issue by emos321** [everpress-co/mailster-block-forms#5]
### Describe the bug

 **I would like to use blocks with GenerateBlock but they are not visible in the editor.**

### Steps to Reproduce

Explained in the pictures below

### Screenshots, screen recording, code snippet

**Block view when editing a post, page, cpt etc. + block settings that are available**

![Screenshot_15](https://user-images.githubusercontent.com/33941097/197332366-b45d0298-5242-4cf6-b00c-2f6740e5f5ab.png)

![Screenshot_1](https://user-images.githubusercontent.com/33941097/197332381-b98f2d4d-7d51-48f0-8b68-b050135e5a69.png)

![Screenshot_6](https://user-images.githubusercontent.com/33941097/197333008-21d60e7c-5e9b-49dc-b321-c1f4758cef5e.png)

**View when editing Mailster Block form + block setting**

![Screenshot_2](https://user-images.githubusercontent.com/33941097/197332416-bb63c4fa-eed3-4252-906c-9b8e3981ed28.png)

![Screenshot_8](https://user-images.githubusercontent.com/33941097/197333033-f2789193-0eda-497b-833e-2801a08497b0.png)

![Screenshot_3](https://user-images.githubusercontent.com/33941097/197332426-09512916-2a5d-4198-8435-15129d210a99.png)

### WordPress information

WP 6.0.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by evrpress** [comment]
Hi!

We currently only support most of the core blocks but there's a filter `mailster_forms_allowed_block_types` you can use:

```php
add_filter(
	'mailster_forms_allowed_block_types',
	function( $blocks ) {

		$blocks[] = 'generateblocks/button-container';
		$blocks[] = 'generateblocks/button';

		return $blocks;
	}
);
```

Please understand that not all blocks work as expected (that's why we only support certain once in the first place)
